import { MODELS } from "./constants";

function sanitize(text) {
  return (text || "").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function exportToMarkdown(topic, discussion, summaries) {
  const lines = [];
  lines.push(`# 3 AI Discussion`);
  lines.push(`**議題:** ${sanitize(topic)}`);
  lines.push(`**日時:** ${new Date().toLocaleString("ja-JP")}`);
  lines.push(`**ラウンド数:** ${discussion.length}`);
  lines.push("");

  discussion.forEach((round, i) => {
    lines.push(`---`);
    lines.push(`## Round ${i + 1}`);
    if (round.userIntervention) {
      lines.push(`> 💬 **司会者:** ${sanitize(round.userIntervention)}`);
      lines.push("");
    }

    round.messages.forEach((msg) => {
      const model = MODELS.find((m) => m.id === msg.modelId);
      const name = model?.name ?? msg.modelId;
      const icon = model?.icon ?? "?";
      lines.push(`### ${icon} ${name}`);
      if (msg.error) {
        lines.push(`*エラー: ${sanitize(msg.error)}*`);
      } else {
        lines.push(sanitize(msg.text));
      }
      lines.push("");
    });

    const summary = summaries[i];
    if (summary && !summary.error) {
      lines.push(`### 📊 サマリー`);
      if (summary.agreements?.length) {
        lines.push(`**合意点:**`);
        summary.agreements.forEach((a) => lines.push(`- ${sanitize(a.point)}`));
      }
      if (summary.disagreements?.length) {
        lines.push(`**対立点:**`);
        summary.disagreements.forEach((d) => lines.push(`- ${sanitize(d.point)}`));
      }
      if (summary.unresolved?.length) {
        lines.push(`**未解決:**`);
        summary.unresolved.forEach((u) => lines.push(`- ${sanitize(u.point)}`));
      }
      if (summary.positionChanges?.length) {
        lines.push(`**立場変化:**`);
        summary.positionChanges.forEach((p) => lines.push(`- ${sanitize(p.ai)}: ${sanitize(p.description)}`));
      }
      lines.push("");
    }
  });

  lines.push(`---`);
  lines.push(`*Generated by [3 AI Discussion](https://github.com/hideosugimoto/ai-discussion)*`);

  return lines.join("\n");
}

export function downloadMarkdown(topic, discussion, summaries) {
  const md = exportToMarkdown(topic, discussion, summaries);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const safeName = topic.slice(0, 30).replace(/[/\\?%*:|"<>]/g, "_");
  const a = document.createElement("a");
  a.href = url;
  a.download = `discussion_${safeName}_${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
