import { MODELS } from "./constants";

function sanitize(text) {
  return (text || "")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]");
}

export function exportToMarkdown(topic, discussion, summaries) {
  const lines = [];
  lines.push(`# 3 AI Discussion`);
  lines.push(`**議題:** ${sanitize(topic)}`);
  lines.push(`**日時:** ${new Date().toLocaleString("ja-JP")}`);
  lines.push(`**ラウンド数:** ${discussion.length}`);
  lines.push("");

  discussion.forEach((round, i) => {
    lines.push(`---`);
    lines.push(`## Round ${i + 1}`);
    if (round.userIntervention) {
      lines.push(`> 💬 **司会者:** ${sanitize(round.userIntervention)}`);
      lines.push("");
    }

    round.messages.forEach((msg) => {
      const model = MODELS.find((m) => m.id === msg.modelId);
      const name = model?.name ?? msg.modelId;
      const icon = model?.icon ?? "?";
      lines.push(`### ${icon} ${name}`);
      if (msg.error) {
        lines.push(`*エラー: ${sanitize(msg.error)}*`);
      } else {
        lines.push(sanitize(msg.text));
      }
      lines.push("");
    });

    const summary = summaries[i];
    if (summary && !summary.error) {
      lines.push(`### 📊 サマリー`);
      if (summary.agreements?.length) {
        lines.push(`**合意点:**`);
        summary.agreements.forEach((a) => lines.push(`- ${sanitize(a.point)}`));
      }
      if (summary.disagreements?.length) {
        lines.push(`**対立点:**`);
        summary.disagreements.forEach((d) => lines.push(`- ${sanitize(d.point)}`));
      }
      if (summary.unresolved?.length) {
        lines.push(`**未解決:**`);
        summary.unresolved.forEach((u) => lines.push(`- ${sanitize(u.point)}`));
      }
      if (summary.positionChanges?.length) {
        lines.push(`**立場変化:**`);
        summary.positionChanges.forEach((p) => lines.push(`- ${sanitize(p.ai)}: ${sanitize(p.description)}`));
      }
      lines.push("");
    }
  });

  lines.push(`---`);
  lines.push(`*Generated by [3 AI Discussion](https://github.com/hideosugimoto/ai-discussion)*`);

  return lines.join("\n");
}

// ── HTML Export ───────────────────────────────────────────────

const AI_COLORS_STATIC = { claude: "#c47b1a", chatgpt: "#285240", gemini: "#2e7db8" };

function sanitizeHtml(text) {
  return (text || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

export function exportToHtml(topic, discussion, summaries) {
  const rounds = discussion.map((round, i) => {
    const intervention = round.userIntervention
      ? `<div style="background:#f0f4ff;border-left:3px solid #7c3aed;padding:8px 14px;margin-bottom:16px;border-radius:0 8px 8px 0;font-size:13px;color:#555">💬 <strong>司会者:</strong> ${sanitizeHtml(round.userIntervention)}</div>`
      : "";

    const messages = round.messages.map((msg) => {
      const model = MODELS.find((m) => m.id === msg.modelId);
      const name = model?.name ?? msg.modelId;
      const icon = model?.icon ?? "?";
      const color = AI_COLORS_STATIC[msg.modelId] || "#666";
      const content = msg.error
        ? `<span style="color:#b91c1c">⚠ ${sanitizeHtml(msg.error)}</span>`
        : sanitizeHtml(msg.text).replace(/\n/g, "<br>");
      return `<div style="border-left:3px solid ${color};padding:12px 16px;margin-bottom:12px;background:#fafafa;border-radius:0 8px 8px 0">
        <div style="font-weight:600;color:${color};margin-bottom:6px;font-size:14px">${icon} ${name}</div>
        <div style="font-size:13px;line-height:1.8;color:#333">${content}</div>
      </div>`;
    }).join("");

    const summary = summaries[i];
    let summaryHtml = "";
    if (summary && !summary.error) {
      const sections = [];
      if (summary.agreements?.length) {
        sections.push(`<div style="margin-bottom:8px"><strong style="color:#16a34a">合意点:</strong><ul style="margin:4px 0">${summary.agreements.map((a) => `<li>${sanitizeHtml(a.point)}</li>`).join("")}</ul></div>`);
      }
      if (summary.disagreements?.length) {
        sections.push(`<div style="margin-bottom:8px"><strong style="color:#b91c1c">対立点:</strong><ul style="margin:4px 0">${summary.disagreements.map((d) => `<li>${sanitizeHtml(d.point)}</li>`).join("")}</ul></div>`);
      }
      if (summary.unresolved?.length) {
        sections.push(`<div style="margin-bottom:8px"><strong style="color:#ca8a04">未解決:</strong><ul style="margin:4px 0">${summary.unresolved.map((u) => `<li>${sanitizeHtml(u.point)}</li>`).join("")}</ul></div>`);
      }
      if (summary.positionChanges?.length) {
        sections.push(`<div style="margin-bottom:8px"><strong style="color:#7c3aed">立場変化:</strong><ul style="margin:4px 0">${summary.positionChanges.map((p) => `<li>${sanitizeHtml(p.ai)}: ${sanitizeHtml(p.description)}</li>`).join("")}</ul></div>`);
      }
      if (sections.length) {
        summaryHtml = `<div style="background:#f8f5ff;border:1px solid #e0d8f0;border-radius:8px;padding:14px;margin-top:8px">
          <div style="font-weight:600;margin-bottom:8px;font-size:13px">📊 サマリー</div>
          ${sections.join("")}
        </div>`;
      }
    }

    return `<section style="margin-bottom:32px">
      <h2 style="font-size:16px;color:#444;border-bottom:1px solid #e0e0e0;padding-bottom:8px;margin-bottom:16px">Round ${i + 1}</h2>
      ${intervention}${messages}${summaryHtml}
    </section>`;
  }).join("");

  return `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>3 AI Discussion - ${sanitizeHtml(topic)}</title>
<style>
  body { font-family: -apple-system, 'Noto Sans JP', sans-serif; max-width: 800px; margin: 0 auto; padding: 24px 16px; background: #fff; color: #333; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  .meta { font-size: 12px; color: #888; margin-bottom: 24px; }
  @media print { body { max-width: 100%; } }
</style>
</head>
<body>
<h1>3 AI Discussion</h1>
<div style="font-size:15px;font-weight:600;color:#222;margin-bottom:4px">議題: ${sanitizeHtml(topic)}</div>
<div class="meta">${new Date().toLocaleString("ja-JP")} · ${discussion.length}ラウンド</div>
${rounds}
<footer style="border-top:1px solid #e0e0e0;padding-top:12px;margin-top:24px;font-size:11px;color:#aaa">
  Generated by <a href="https://github.com/hideosugimoto/ai-discussion" style="color:#7c3aed">3 AI Discussion</a>
</footer>
</body>
</html>`;
}

export function downloadHtml(topic, discussion, summaries) {
  const html = exportToHtml(topic, discussion, summaries);
  const blob = new Blob([html], { type: "text/html;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const safeName = topic.slice(0, 30).replace(/[/\\?%*:|"<>]/g, "_") || "untitled";
  const a = document.createElement("a");
  a.href = url;
  a.download = `discussion_${safeName}_${Date.now()}.html`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadMarkdown(topic, discussion, summaries) {
  const md = exportToMarkdown(topic, discussion, summaries);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const safeName = topic.slice(0, 30).replace(/[/\\?%*:|"<>]/g, "_") || "untitled";
  const a = document.createElement("a");
  a.href = url;
  a.download = `discussion_${safeName}_${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}
